Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", automount: true

  config.vm.define "melperriS" do |s|
    s.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "melperriS"]
      vb.customize ["setproperty", "machinefolder", "/mnt/nfs/homes/melperri/sgoinfre/melperriS"]
      vb.memory = "4096"
      vb.cpus = 2
    end
    s.vm.provision "shell", inline: "echo [INFO]  Hello Server"
    s.vm.hostname = "melperriS"
    s.vm.network "private_network", ip: "192.168.56.110", hostname: true
    s.vm.provision "shell", inline:<<-SHELL
    sudo ln -s /sbin/ifconfig /usr/bin/ifconfig
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --bind-address 192.168.56.110 --flannel-iface eth1
	sleep 5
	cp /vagrant/*.yml /home/vagrant/.
	echo 'alias k="kubectl"' >> /home/vagrant/.bashrc
    SHELL
  end
end
#sudo apt update -y
#sudo apt upgrade -y
#sudo apt clean
