Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "melperri"]
    vb.memory = "1024"
    vb.cpus = 1
  end
  config.vm.provision "shell", inline:<<-SHELL
  echo '========================='
  SHELL
  config.vm.hostname = "melperriS"
  config.vm.network "public_network", ip: "192.168.56.110", hostname: true
end
