apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
spec:
  destination:
    name: mycluster
    namespace: dev
    server: ''
  source:
    path: playground
    repoURL: wil42/playground
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
